# Generated by Django 4.2.4 on 2023-09-04 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_rename_retal_period_book_rental_period_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='total_r',
            new_name='total_rental',
        ),
    ]
